### ISSUE TITLE
Te falta el ;

### ISSUE THREAD

**Issue by juanmicosta** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-alexrrlm#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-alexrrlm/blob/c8fbcfb48d3a401c80e5d2dacf758feb666695cf/programa.java#L36

**Comment by alexrrlm** [comment]
Vale ahora lo veo.

**Comment by alexrrlm** [comment]
Listo corregido
